import type { Metadata } from "next";
import { Geist, Geist_Mono,Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const inter = Inter({ subsets: ["latin"] })

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}   h-full antialiased`}
    >
      <body className="min-h-screen bg-zinc-50">
        <div className="dotted-frame mx-auto flex min-h-screen w-full max-w-none sm:max-w-6xl flex-col bg-white">
          {children}
        </div>
        <Analytics />
      </body>
    </html>
  );
}
